// <auto-generated />
using ComicShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicShop.Migrations
{
    [DbContext(typeof(ComicContex))]
    [Migration("20201004202611_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicShop.Models.Comic", b =>
                {
                    b.Property<int>("ComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ComicId");

                    b.HasIndex("PublisherID");

                    b.ToTable("Comics");

                    b.HasData(
                        new
                        {
                            ComicId = 1,
                            PublisherID = 2,
                            Rating = 5,
                            Title = "Batman #608",
                            Year = 2019
                        },
                        new
                        {
                            ComicId = 2,
                            PublisherID = 2,
                            Rating = 5,
                            Title = "Superman Vs. Darkseid",
                            Year = 2015
                        },
                        new
                        {
                            ComicId = 3,
                            PublisherID = 3,
                            Rating = 5,
                            Title = "Spawn #306",
                            Year = 2020
                        },
                        new
                        {
                            ComicId = 4,
                            PublisherID = 1,
                            Rating = 3,
                            Title = "The Tomb of Dracula",
                            Year = 1973
                        },
                        new
                        {
                            ComicId = 5,
                            PublisherID = 1,
                            Rating = 4,
                            Title = "True Believers #1 - Venom Carnage",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("ComicShop.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherID = 1,
                            PublisherName = "Marvel Studios"
                        },
                        new
                        {
                            PublisherID = 2,
                            PublisherName = "DC Comics"
                        },
                        new
                        {
                            PublisherID = 3,
                            PublisherName = "Image Comics"
                        });
                });

            modelBuilder.Entity("ComicShop.Models.Comic", b =>
                {
                    b.HasOne("ComicShop.Models.Publisher", "PublisherClass")
                        .WithMany()
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
